#!/bin/bash
set -e
if [[ ! -e /var/log/php5-fpm.log ]]; then
	# The php log forwarder might be sleeping and waiting
	# until the error log becomes available. We restart it in
	# 1 second so that it picks up the new log file quickly.
	(sleep 1 && sv restart /etc/service/php-log-forwarder)
fi
exec /usr/sbin/php5-fpm
